### ISSUE TITLE
Expose client_order_id for nash

### ISSUE THREAD

**Issue by jankjr** [nash-io/openlimits#148]
We will need to expose the field in nash-rust as well.

**Comment by Bi0max** [comment]
@jankjr is it planned to implement client_order_id in the near future? Without it, it's very hard to track your orders. E.g. what if order is created, but returned "order_id" is not saved due to some bug or problem with DB (anything can happen). Then system will completely lose track of the order.

**Comment by jankjr** [comment]
I think we added some support for clientIds some while back. But @notdanilo will know more.

**Comment by notdanilo** [comment]
I need to check the support state.

**Comment by Bi0max** [comment]
@jankjr @notdanilo . This functionality seems to be not implemented neither for JS, nor for Rust/Python clients.
