### ISSUE TITLE
gmp.lib on Windows

### ISSUE THREAD

**Issue by notdanilo** [nash-io/openlimits#167]
1. We need to describe the installation of `gmb.lib` on Windows in the docs.
2. We need to install gmb.lib in our GitHub Action's Windows test environment.

Reference:
https://github.com/ZenGo-X/kms-secp256k1/issues/25
https://github.com/vhnatyk/gmp-release
https://github.com/TonyBogdanov/zip

**Comment by caiocesarbosco** [comment]
After 5 days breaking my brain out, i've finally found this issue. It works for Windows 32 bit. Maybe the next step is provide gmp.lib and gmp.dll compiled for Windows x64.

I've found this related to it: 

https://stackoverflow.com/questions/4711315/build-gmp-on-64bit-windows

**Comment by notdanilo** [comment]
@caiocesarbosco making the library more accessible is definitely something we want to achieve. I will make sure to redist the deps.

**Comment by VCasecnikovs** [comment]
Are there any Windows friendly alternatives?
