### ISSUE TITLE
Hope to provide a unified symbol and market id

### ISSUE THREAD

**Issue by milescui** [nash-io/openlimits#190]
Hope to provide a unified symbol.

refer ccxt: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by notdanilo** [comment]
@milescui I am currently working on a huge refactoring and we do plan to define statically typed symbols.

**Comment by milescui** [comment]
@notdanilo I am very excited.

**Comment by notdanilo** [comment]
@milescui please check the latest version of the API
