### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by steffenix** [nash-io/openlimits#26]

**Comment by jnicholls** [comment]
I will be integrating [tarpaulin](https://github.com/xd009642/tarpaulin) into the GitHub Actions of the project to run code completion analysis on the tests.

**Comment by jnicholls** [comment]
Would we like to use a code coverage service, such as https://codecov.io or https://coveralls.io/ @steffenix?

**Comment by steffenix** [comment]
I do not have any strong opinions on code coverage tool.

I had issues in the past with codecov it was timing out a lot.

**Comment by steffenix** [comment]
The library doesn't compile on mac os.
https://github.com/xd009642/tarpaulin/issues/152
