### ISSUE TITLE
Add trades history

### ISSUE THREAD

**Issue by steffenix** [nash-io/openlimits#31]
- Add trade history to the binance and coinbase SDK
- Add the wrapper and data structures for a openlimits trade
- Add get_trade_history trait to the Exchange traits

Binance: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#account-trade-list-user_data

Coinbase:
https://docs.pro.coinbase.com/#fills

Openlimits:

Example:

get_trades(pair_name)

Data structure:

```
    "time": u64,
    "trade_id":Depending on the exchange type,
    "price": Decimal,
    "size": Decimal,
    "side": Side Type

```

**Comment by acatinon** [comment]
Are you talking about "Account trades list" (`/api/v3/myTrades` on Binance) or "Recent trades list" (`/api/v3/trades`)?

**Comment by steffenix** [comment]
For binance it should be /api/v3/myTrades

**Comment by acatinon** [comment]
I started to have a look at this, there is the data structure I extracted from the APIs so far:

```Rust
#[derive(Clone, Constructor, Debug)]
pub struct Trade<T, O> {
    pub id: T,
    pub order_id: O,
    pub pair: String,
    pub price: Decimal,
    pub qty: Decimal,
    pub fees: Decimal,
    pub side: Side,
    pub liquidity: Option<Liquidity>,
    pub created_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum Liquidity {
    Maker,
    Taker,
}
```

What do you think?

Btw I think the correct API call for Coinbase is [/fills](https://docs.pro.coinbase.com/#fills), not [/products/\<product-id\>/trades](https://docs.pro.coinbase.com/#get-trades) (the latter is not authenticated).

**Comment by steffenix** [comment]
That's a good start, we will change the pair type for the overall project.

**Comment by acatinon** [comment]
On Coinbase, order ids are strings, but trade ids are integers.

What do you think about renaming `IdType` to `OrderIdType` and adding `TradeIdType` ?
