### ISSUE TITLE
Historic rates

### ISSUE THREAD

**Issue by steffenix** [nash-io/openlimits#36]
## Exchanges endpoints

- [binance](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#klinecandlestick-data)
- [coinbase](https://docs.pro.coinbase.com/#get-historic-rates)

## OpenLimits

Function:

```
get_historic_rates
```

Data format: 

```
{
  time:  u64,
  low: Decimal,
  high: Decimal,
  open: Decimal,
  clone: Decimal,
  volume: Decimal
}
```

**Comment by acatinon** [comment]
I'm on it.
