### ISSUE TITLE
Terminology: symbol vs pair

### ISSUE THREAD

**Issue by acatinon** [nash-io/openlimits#43]
In the openLimits models there are both terminologies (symbol and pair) for the same thing, witch may be confusing.

For instance:

```Rust
#[derive(Clone, Constructor, Debug)]
pub struct Order<T> {
    pub id: T,
    pub symbol: String, // <------------------------------------
    pub client_order_id: Option<String>,
    pub created_at: DateTime<Utc>,
}

#[derive(Clone, Constructor, Debug)]
pub struct CancelOrderRequest<T> {
    pub id: T,
    pub pair: Option<String>, // <------------------------------------
}
```

I think it could be harmonized, but which term to choose?

**Comment by steffenix** [comment]
Yes indeed we need to find the terminologies we want to use. There will be a review of all of that when with the code from this issue https://github.com/nash-io/openlimits/issues/29

**Comment by steffenix** [comment]
I think we should use market

The market object containing market information such as the pair and the precision data.

**Comment by steffenix** [comment]
I suggest we use `market_pair`
