### ISSUE TITLE
Open Telegram Group?

### ISSUE THREAD

**Issue by mankinskin** [nash-io/openlimits#46]
Hi, I am new to this project, and I must say that I found the slack chat room very inaccessible and complicated to find. I am using Telegram for other projects, or basically any chatting at all, already, and it is very versatile and accessible. I would like to suggest opening a telegram group for this project aswell, to make it more accessible.

**Comment by steffenix** [comment]
What is the issue with slack?
A telegram group will create a lot of noise as all the conversation are on the same room.

I am not using telegram.

**Comment by canesin** [comment]
Thanks for the suggestion @mankinskin , but coordinating code on TG is really hard.

To enter the a project slack all one needs to do is [click here to be invited](https://join.slack.com/t/openlimitsworkspace/shared_invite/zt-gdtstuma-ea2cIR_tpwavCuY5uLw1VQ) to join.

**Comment by mankinskin** [comment]
> A telegram group will create a lot of noise as all the conversation are on the same room. The discussion can also happen on github.
Oh right I did not think about that. Many projects have telegram groups for a general chat, thats where I got that idea. In that case you would of course need something like slack or discord.

> What is the issue with slack?
Personally, I have only had mediocre experiences with slack, due to the complexity of getting into a project. You need an invite, then you get an account for every workspace, with different passwords and so on. I don't really like the experience.

I would favor discord (obviously we need chat rooms), but that is just something on my personal wishlist.
