### ISSUE TITLE
Binance web socket stream disconnects

### ISSUE THREAD

**Issue by fabianboesiger** [nash-io/openlimits#67]
The [binance web socket API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md) doc states that:

> The websocket server will send a ping frame every 3 minutes. If the websocket server does not receive a pong frame back from the connection within a 10 minute period, the connection will be disconnected. Unsolicited pong frames are allowed.

**Comment by fabianboesiger** [comment]
Please check out PR #68. Note that I am relatively new to Rust and especially streams, so feedback is welcome.

**Comment by acatinon** [comment]
This issue can be closed, see discussions on PR #68
