### ISSUE TITLE
Slack Invite in Readme is dead

### ISSUE THREAD

**Issue by Michael-J-Ward** [nash-io/openlimits#87]
The project slack link in the read me is no longer valid. Is the slack community still active?

https://openlimitsworkspace.slack.com/join/shared_invite/zt-gdtstuma-ea2cIR_tpwavCuY5uLw1VQ#/

**Comment by sanderdms** [comment]
Last post I see in that Slack is from September 6th. Looks abandoned from my POV.

**Comment by tarcieri** [comment]
I'd also be interested in joining this Slack

**Comment by acatinon** [comment]
Is [this link](https://join.slack.com/t/openlimitsworkspace/shared_invite/zt-haf4kuf7-k7FIRqYbXWCtHxfUqYUNLA) working ?

**Comment by Michael-J-Ward** [comment]
Yes!
